language: java
jdk:
  - oraclejdk8

sudo: required

# safelist
branches:
  only:
  - master
  - develop
  - /^support.*$/

notifications:
  email: false
  slack:
    rooms:
      - aaan:nPcmtLyPdpi69PCnz3alvwRl#development
    on_success: change
    on_failure: change

services:
  - rabbitmq
  - mongodb

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - cd BusinessLogic/
  - ./gradlew test -i
  - cd ../Database/
  - ./gradlew test -i
  - cd ../Frontend/
  - ./gradlew test -i
  - cd ../GmailPolling/
  - ./gradlew test -i
  - cd ../FacebookPolling/
  - ./gradlew test -i
